version: '3.8'

services:
  # 1. Veritabanı bloğu
  redis_db:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 2. Hava Durumunu Çekiyoruz
  weather_worker:
    build:
      context: .
      dockerfile: Dockerfile.weather
    depends_on:
      - redis_db
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_db

  # 3. API
  weather_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - redis_db
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_db